#!/usr/bin/env python3
"""Compose the pinned upstream K-Bot MJCF with Trion worksite W1.

The source models remain independently owned: robot geometry stays in the
pinned kscale-assets submodule and the fixture stays in TRION/sim/worksites.
Composition rewrites mesh references to absolute paths in memory, so callers
can load the merged XML from any working directory without copying assets.
"""

from __future__ import annotations

import argparse
import math
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import mujoco
import numpy as np

TRION_DIR = Path(__file__).resolve().parents[1]
REPO_ROOT = TRION_DIR.parent
DEFAULT_ROBOT = (
    REPO_ROOT
    / "ksim-kbot"
    / "ksim_kbot"
    / "kscale-assets"
    / "kbot-v2-lw-feet"
    / "robot.mjcf"
)
DEFAULT_WORKSITE = Path(__file__).resolve().parent / "worksites" / "w1_panel.xml"


def _section(root: ET.Element, tag: str) -> ET.Element:
    found = root.find(tag)
    if found is None:
        found = ET.SubElement(root, tag)
    return found


def compose_xml(robot_path: Path, worksite_path: Path) -> str:
    if not robot_path.is_file():
        raise FileNotFoundError(
            f"K-Bot MJCF not found at {robot_path}; initialize the nested "
            "ksim-kbot/ksim_kbot/kscale-assets submodule"
        )
    if not worksite_path.is_file():
        raise FileNotFoundError(f"W1 worksite MJCF not found at {worksite_path}")

    robot = ET.parse(robot_path).getroot()
    worksite = ET.parse(worksite_path).getroot()
    robot.set("model", "trion_w1_kbot_composed")

    # The pinned asset was generated by a newer MuJoCo exporter. This default
    # hint is optional and unsupported by the Phase 0 CI version (3.1.6).
    for mesh_default in robot.findall(".//default/mesh"):
        mesh_default.attrib.pop("maxhullvert", None)

    robot_asset = _section(robot, "asset")
    for mesh in robot_asset.findall("mesh"):
        mesh_file = mesh.get("file")
        if mesh_file and not Path(mesh_file).is_absolute():
            mesh.set("file", str((robot_path.parent / mesh_file).resolve()))

    fixture_asset = worksite.find("asset")
    if fixture_asset is not None:
        robot_asset.extend(list(fixture_asset))

    robot_world = _section(robot, "worldbody")
    fixture_world = worksite.find("worldbody")
    if fixture_world is not None:
        robot_world.extend(list(fixture_world))

    # The robot owns compiler/default/actuator/sensor configuration. W1 owns
    # the global physics and lighting used for this composed acceptance scene.
    for tag in ("option", "visual"):
        element = worksite.find(tag)
        if element is not None:
            existing = robot.find(tag)
            if existing is not None:
                robot.remove(existing)
            robot.insert(0, element)

    return ET.tostring(robot, encoding="unicode")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--robot", type=Path, default=DEFAULT_ROBOT)
    parser.add_argument("--worksite", type=Path, default=DEFAULT_WORKSITE)
    parser.add_argument("--steps", type=int, default=100)
    args = parser.parse_args()
    if args.steps < 0:
        parser.error("--steps must be non-negative")

    try:
        xml = compose_xml(args.robot, args.worksite)
        model = mujoco.MjModel.from_xml_string(xml)
    except (FileNotFoundError, ET.ParseError, ValueError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1

    data = mujoco.MjData(model)
    for _ in range(args.steps):
        mujoco.mj_step(model, data)

    robot_id = mujoco.mj_name2id(
        model, mujoco.mjtObj.mjOBJ_BODY, "floating_base_link"
    )
    panel_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "panel")
    plug_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "plug")
    required_sites = (
        "handle_grip_site",
        "latch_tab_site",
        "socket_entry_site",
        "plug_grip_site",
    )
    sites_present = all(
        mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, name) >= 0
        for name in required_sites
    )
    finite_state = bool(np.isfinite(data.qpos).all() and np.isfinite(data.qvel).all())
    robot_z = float(data.xpos[robot_id][2])
    plug_z = float(data.xpos[plug_id][2])

    print(f"robot source:   {args.robot}")
    print(f"worksite source:{args.worksite}")
    print(
        f"bodies: {model.nbody}  joints: {model.njnt}  actuators: {model.nu}  "
        f"sim time: {data.time:.2f} s"
    )
    print(f"robot z: {robot_z:.3f}  plug z: {plug_z:.3f}")

    if robot_id < 0 or panel_id < 0 or plug_id < 0 or not sites_present:
        print("FAIL: composed scene is missing required named objects", file=sys.stderr)
        return 1
    if not finite_state or not math.isfinite(robot_z) or robot_z < 0.0:
        print("FAIL: composed simulation became unstable", file=sys.stderr)
        return 1
    if not 0.7 < plug_z < 1.0:
        print("FAIL: W1 plug left its stable tray region", file=sys.stderr)
        return 1

    print("OK: pinned K-Bot and W1 load and step as one composed model")
    return 0


if __name__ == "__main__":
    sys.exit(main())
